maith_common_translator:
  resource: "@MaithCommonTranslatorBundle/Controller/"
  type:     annotation
  prefix:   /admin/translations
  #
  #resource: "@MaithCommonTranslatorBundle/Resources/config/routing.yml"
  #prefix:   /