parameters:
    contact-email-from: info@info.com
    contact-email-from-name: 'Rodrigo Santellan'
    contact-email-to: info@info.com
    contact-email-subject: '[SUM] Contacto desde sitio web'
    becas-email-from: info@info.com
    becas-email-from-name: 'Rodrigo Santellan'
    becas-email-to: info@info.com
    becas-email-subject: '[SUM] Becas'