parameters:
    contact-email-from: laura@lauranozar.com
    contact-email-from-name: 'Sociedad Uruguaya de Microbiología'
    contact-email-to: laura@lauranozar.com
    contact-email-subject: '[SUB] Contacto desde sitio web'
    becas-email-from: laura@lauranozar.com
    becas-email-from-name: 'Sociedad Uruguaya de Microbiología'
    becas-email-to: laura@lauranozar.com
    becas-email-subject: '[SUB] Becas'
